repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort project tests
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black project tests
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        types: [python]
        pass_filenames: false

